### ISSUE TITLE
Py3.4

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#10]
Я так и думал- enum+ Pathlib появились в Питон3.4, я это вспомнил
А у меня в Вин32- Питон3.3 встроенный,вот облом =(

**Comment by Alexey-T** [comment]
Enum выкинул, получилось-
~~~
SERVER = 0
DIRECTORY = 1
FILE = 2

icons = (
            "cuda-ftp-icon-server.png",
            "cuda-ftp-icon-directory.png",
            "cuda-ftp-icon-file.png",
        )

потом

        for icon in icons:
            fn = os.path.join(os.path.dirname(__file__), icon)
            tree_proc(self.tree, TREE_ICON_ADD, 0, 0, fn)
~~~

**Comment by pohmelie** [comment]
Не очень понял в чём проблема, но какое отношение sublime имеет к cudatext? Плагин же для cudatext.

**Comment by Alexey-T** [comment]
Cudatext for Win32 -имеет Py3.3 embedded, python33.dll, python32.zip
enum, pathlib don't work in Py3.3, enum is new in Py3.4

**Comment by Alexey-T** [comment]
Не против моего пача?

1.enum. удалю enum (заменю Node, на без него)
2.pathlib. запостю pathlib.py и сделаю from .pathlib import Path

**Comment by pohmelie** [comment]
Вообще странно, что у одного приложения разные версии python для разных платформ. Я вижу следующие решения:
* Поднять версию для всех платформ до 3.4 (а лучше и до 3.5). (лучший вариант)
* Использовать библиотеки pathlib, enum из репозитория python.
* Менять исходный код плагина, чтобы он работал на 3.3. (худший вариант)

**Comment by Alexey-T** [comment]
(Для Мак обычно ставится Py3.5 - он и юзается)
(Для Вин я пока не могу поднять верс.)
