### ISSUE TITLE
Ftp prop: initial dir

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#17]
Oftern ftp clients have opt- a)port, b) initial dir on remote. Shot of SynFTP

![ftp](https://cloud.githubusercontent.com/assets/4154978/15654096/67ce1ca2-26a2-11e6-8997-673808e470f0.png)

is it easy to add?

**Comment by pohmelie** [comment]
Port number option available via address field: `address:port` (`127.0.0.1:8021` for example). Initial remote directory can be done, but these will need to build full tree to path step by step.

**Comment by Alexey-T** [comment]
i saw port already. yes. Init dir: if i add to FTPClient()

    client.cwd('/pub/some')

is it ok for Init dir '/pub/some'?

**Comment by Alexey-T** [comment]
(IMO reading of middle folders not needed, if init dir is "/pub/www/site" then no need to read at start /pub and /pub/www. 
FAR client does like it. it is faster)

**Comment by pohmelie** [comment]
Double panel commanders have `..` item in their list view. So you can go up, but in tree view, if you have no parents, you can't refresh them.

**Comment by Alexey-T** [comment]
It is right.Checked SynFTP for Synwrite, also treeview, init dir fills this dir, no middle dirs touched.

**Comment by pohmelie** [comment]
You mean if I have server as
```
/111/111.txt
/222/222.txt
```
And initial directory is `/111`, then I will see tree like?
```
127.0.0.1:8021@anon
    111.txt
```

**Comment by Alexey-T** [comment]
nop. I mean this, see shot of synftp (middle folders empty)

![syn](https://cloud.githubusercontent.com/assets/4154978/15665875/c2f34478-271e-11e6-8a49-7d932e78e571.png)

**Comment by pohmelie** [comment]
This will not work, since there is no active connection. You can't connect to server. You just refresh paths. Maybe there can be `Go to...` dialog in context menu.

**Comment by Alexey-T** [comment]
Why can not we

- do connection
- do cwd
- add n tree nodes until init-dir
- read init dir
- fill final node

**Comment by pohmelie** [comment]
Which action should start this sequence?

**Comment by Alexey-T** [comment]
some new action. Curr actions cannot doit.

**Comment by pohmelie** [comment]
That's what I speaking about above.

**Comment by pohmelie** [comment]
So, what command name you mean? Should it be `Go to…` with path dialog or something else?

**Comment by Alexey-T** [comment]
"Go to" with dlg_input is good.
Please.
