### ISSUE TITLE
Goto allows bad paths

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#29]
After input of random I got
![di](https://cloud.githubusercontent.com/assets/4154978/15746135/49ec8caa-28e6-11e6-8ef7-6f17a5766b3e.png)

can we do cwd, to test input?

**Comment by pohmelie** [comment]
Fixed in https://github.com/pohmelie/cuda_ftp/commit/57d95645711ac051d5f8937ee07dbc0a864c14f5
