### ISSUE TITLE
Read this ftp

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#30]
addr: ftp.aha.ru
login/pw: default ones

I cannot connect,
read dir: 500 MLSD /: Command not understood

**Comment by Alexey-T** [comment]
@Andreas123456 Maybe u want to see this plugin?

**Comment by pohmelie** [comment]
> read dir: 500 MLSD /: Command not understood

ftp server does not support MLSD command, time to update your server. MLSD is from 2007 rfc.

**Comment by Alexey-T** [comment]
hm, it is Big russian server. 
Can make "fallback"?

**Comment by pohmelie** [comment]
@Alexey-T, you can if you want. https://github.com/pohmelie/aioftp/issues/39

**Comment by Alexey-T** [comment]
maybe apps have option "Use old style LIST cmd". Per server. Maybe option is ok?

**Comment by pohmelie** [comment]
Fallback is ok, but look at my opinion at link. I definitely will not implement this.
