### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by ildarkhasanshin** [pohmelie/cuda_ftp#37]
[14:38] Read dir: domain.com/: 500 Unknown command

**Comment by pohmelie** [comment]
What is it? Who is owner of this log? What steps to reproduce?

**Comment by ildarkhasanshin** [comment]
type: ftp
host: 10021987.ru
port: 21
username: user47639_tmp
pass: EyWyQGVe
dir: <empty>
timeout: 30
label: <empty>

last ubuntu 16.10
last cuda_ftp (https://github.com/pohmelie/cuda_ftp)
last cudatext 1.5.2.0 linux-x86_64-gtk2, fpc 3.0.0 (https://sourceforge.net/projects/cudatext/files/release/Linux/)

**Comment by pohmelie** [comment]
Can't reproduce with your settings. Everything is fine.
