### ISSUE TITLE
500 MLSD /- command not understood

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#38]
Server on AIX
http://synwrite.sourceforge.net/forums/viewtopic.php?p=10408#p10408

plugin supports MLSD?

**Comment by pohmelie** [comment]
@Alexey-T the right question is "does server support MLSD?", since plugin/client use only MLSD command to determine list of files and directories. It is problem of many old servers, but the suggestion here the only one: change ftp server.

**Comment by Alexey-T** [comment]
hmm.So we need supp of other List cmds. Can u add it? Python can do it maybe

**Comment by Alexey-T** [comment]
Ppl ise their servers. they cannot change it coz of CudaText.

**Comment by pohmelie** [comment]
@Alexey-T, actually we already talk about it #30

**Comment by Alexey-T** [comment]
Done
