### ISSUE TITLE
add hotkeys for navigate by tree

### ISSUE THREAD

**Issue by ildarkhasanshin** [pohmelie/cuda_ftp#43]
for example
enter - open dir
enter/f4 - open for edit

**Comment by Alexey-T** [comment]
Patch welcome
См плагин Testing Dialog API

**Comment by ildarkhasanshin** [comment]
не нашел *плагин Testing Dialog API*
можно подробнее?

**Comment by Alexey-T** [comment]
![screenshot from 2019-01-30 11-06-09](https://user-images.githubusercontent.com/4154978/51966962-13043480-247f-11e9-8a7f-0e2d78944907.png)

**Comment by ildarkhasanshin** [comment]
т.е. treeview нужно добавить 'on_key_up'?

**Comment by Alexey-T** [comment]
В тривью добавить, или onkeyup или onkeydown..

**Comment by Alexey-T** [comment]
Не понял..

**Comment by ildarkhasanshin** [comment]
не вызывается msg_box
когда фокус в treeview плагина
и нажатии любой клавиши

**Comment by Alexey-T** [comment]
Может data приходит не строка?

**Comment by ildarkhasanshin** [comment]
http://wiki.freepascal.org/CudaText_API#Control_events
тут только такие
Events for control "treeview":
"on_fold", "on_unfold": Called before treeview node is folded/unfolded. Param "data" is int handle of treeview node.
"on_select": Called after selection is changed.

**Comment by Alexey-T** [comment]
Попробуй вывести не data а repr(data)

**Comment by ildarkhasanshin** [comment]
без изменений
судя по api on_key.. ведь действуют только для editor?

**Comment by Alexey-T** [comment]
"on_key_down": Called when key is pressed in form (form should have "keypreview":True). If plugin returns False, key is blocked. 

значит что on_key*** надо давать не дереву а форме. причем еще бы поставить форме "keypreview":True.

**Comment by ildarkhasanshin** [comment]
> значит что on_key*** надо давать не дереву а форме
с этим, думаю, пока что не справлюсь..

**Comment by Alexey-T** [comment]
добавил Space == dbl click.

**Comment by ildarkhasanshin** [comment]
кому удобнее через enter
то изменить 0x20 на 0x0D

**Comment by ildarkhasanshin** [comment]
https://github.com/pohmelie/cuda_ftp/pull/45
