### ISSUE TITLE
Unable to Edit/Remove Server

### ISSUE THREAD

**Issue by noctisdb** [pohmelie/cuda_ftp#46]
TypeError: get_server_by_short_info() takes 3 positional arguments but 4 were given

Windows 10

**Comment by Alexey-T** [comment]
I just made new server for ftp.aha.ru and edited it and deleted. Need more details. ftp/sftp? special values in server dialog?

**Comment by noctisdb** [comment]
I can manually edit the details and refresh to remove, the interface doesnt work though.
{
  "servers": [
    {
      "login": "echo@noctis.org",
      "use_list": false,
      "label": "NoctisFTP",
      "port": "21",
      "init_dir": "/home3/noctisor/",
      "timeout": "30",
      "address": "noctis.org",
      "type": "ftp",
      "password": "passwordremoved"
    }
  ]
}

Using the interface gives the error, manually setting the values and reloading, then double clicking on the server also does this.  I looked over the source and I don't see anything that could be causing it.  address I tried putting in the ftp(which I took out once I realized function does this).

**Comment by Alexey-T** [comment]
@pohmelie I confirm - i added server to settings/cuda_ftp.json - from the text above.

**Comment by Alexey-T** [comment]
Try removing the plugin; then AddonManager/ Install from github, enter URL
https://github.com/pohmelie/cuda_ftp
made fix. better?

**Comment by noctisdb** [comment]
All working as intended!

**Comment by Alexey-T** [comment]
(Feel free to tell about issues in Nim lexer. in Cudatext repo.)

**Comment by pohmelie** [comment]
Oops, my bad. Your fix looks ok.
