### ISSUE TITLE
SFTP connection failed: Please install Paramiko lib

### ISSUE THREAD

**Issue by dinkumoil** [pohmelie/cuda_ftp#48]
I tried to connect to the following demo SFTP server using _CudaText_ 64 bit v1.90.0.0 for Windows with latest version of the FTP plugin 2019.02.17 (SFTP support plugin installed as well, 2017.09.09.2):

Host: test.rebex.net
Port: 22
User: demo
PW: password

The connection failed with the error message "Please install 'Paramiko' library for SFTP support".

I was able to track down the error to file `cuda_ftp_libs\x64\bcrypt\__init__.py` line 25 (`from bcrypt import _bcrypt`). This line is the first failing line in the attempt to import _paramiko_ lib, which is started in file `cuda_ftp\__init__.py` line 24 (`import paramiko`). 

The binary file whose import failed (named `_bcrypt.pyd`) is present.

I have tested _CudaText_ 32 bit as well, same failure.

Further investigations have shown, that `_bcrypt.pyd` wants to import `python35.dll` which doesn't exist anymore due to Python update some versions of _CudaText_ ago.

**Comment by Alexey-T** [comment]
Need to update sftp libs, using python 3.6 version

**Comment by Alexey-T** [comment]
I will fix it for Py36, ie will make separate plugin with py36 DLLs.
how to do it: go to PyPI.org, download all packages, replaces folders in plugin. test it then.

**Comment by Alexey-T** [comment]
Addon is added:
SFTP support for FTP, Windows x32/x64, Python 3.6

it works on my Win10 x64+x32.
pls test.

**Comment by dinkumoil** [comment]
It works with the test server provided above. Did no further testing.

Thank you!

**Comment by Alexey-T** [comment]
@dinkumoil Pls reinstall SFTP support libs, i changed its subdir in "py", and changed FTP plugin
