### ISSUE TITLE
FTP plugin doesn't suport login by ssh certificate (in SFTP mode)

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#49]
See text from https://github.com/Alexey-T/CudaText/issues/2390
(closed but not solved)

**Comment by Alexey-T** [comment]
@OlehL
Pls see #49, #47 
Could you solve/add these features, for donation? (donation sum will be like ~~before).

**Comment by OlehL** [comment]
I don't use ftp or sftp, so I can't help.

**Comment by Alexey-T** [comment]
2021.03.06
+ add: SFTP public key authentication support (work by @halfbrained)
