### ISSUE TITLE
menuitem 'History' for folders?

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#65]
@ildarkhasanshin If I do "Go to folder" in the context menu, 'History' list is not having this new folder. it's ok?

**Comment by ildarkhasanshin** [comment]
https://github.com/pohmelie/cuda_ftp/pull/66

**Comment by Alexey-T** [comment]
@ildarkhasanshin 
идейка. сделать список (меню) как в куде. Там показывает имена так

имяфайла (имя папки)

при этом удобно сделать CLIP_MIDDLE. начало папки и конец папки почти всегда влезут. а имя точно влезет.
