### ISSUE TITLE
menu for Srv

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#7]
wish: menu for serv shoud have(too)
 
- Connect
- Disconnect (remove child nodes from srv; quit ftp)

**Comment by pohmelie** [comment]
> connect
> disconnect
It have no point, since there is no established connection between «requests». Every time you want list some dir, open file, save file new connection to server are made. And right after job is done ftp quit called.
> make file/dir--no need
So you can't create root file/dir? What's the point?

**Comment by Alexey-T** [comment]
make file/dir--no need===Ops, I need it. make file/dir needed.
