### ISSUE TITLE
ftp log error on Ctrl+R on selected file

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#85]
@ildarkhasanshin 
выделен файл readme.txt.
ctrl+R ==> ошибка в логе ftp

![Screenshot from 2022-05-07 09-37-58](https://user-images.githubusercontent.com/4154978/167242194-f18d0f99-abc0-4ec6-91d7-51bd19e36daf.png)

**Comment by Alexey-T** [comment]
повтор на ftp.scene.org !
ошибка другая

![Screenshot from 2022-05-07 09-39-27](https://user-images.githubusercontent.com/4154978/167242210-2c14e393-80b0-46bc-96a4-2da6e6daf9f6.png)

**Comment by ildarkhasanshin** [comment]
> повтор на ftp.scene.org !
> ошибка другая

https://github.com/pohmelie/cuda_ftp/pull/86

**Comment by ildarkhasanshin** [comment]
протестируйте на всех трех ftp
